### ISSUE TITLE
bug in pandas_market_calendars 4.0

### ISSUE THREAD

**Issue by brettelliot** [Lumiwealth/lumibot#201]
Hi all,

Attempting to test out lumibot but can't get the getting started backtest to work. With a fresh venv of python 3.9.13 and after a `pip install lumibot` I run the sample code in the getting started guide. I get this error:

```ValueError: cannot reindex on an axis with duplicate labels```

On line 42 of helpers.py:

```days = nyse.schedule(start_date="1950-01-01", end_date=today)```

It seems like this is a known issue of pandas_market_calendars 4.0 and is fixed in 4.0.1. However, 4.0.1 doesn't exist on pypi and 4.0 seems to be a hardcoded dependency.

https://github.com/rsheftel/pandas_market_calendars/pull/215

Can anyone help me get lumibot installed? Wouldn't this issue impact fresh deployments of pre-existing users?

Thanks,
Brett

**Comment by grzesir** [comment]
Yes currently v4.0 has bugs. You need to downgrade to v3.6. We will add this to Lumibot by default soon

pip uninstall pandas_market_calendars
pip install pandas_market_calendars==3.6

**Comment by grzesir** [comment]
fixed in pandas_market_calendars v4.1.2
