### ISSUE TITLE
Yesterday's dividends unavailable in Interactive Brokers API

### ISSUE THREAD

**Issue by neilsmurphy** [Lumiwealth/lumibot#34]
This has been discussed in Discord, but logging the issue here as well. 

Lumibot has a method `get_yesterday_dividend` and `get_yesterday_dividends` which returns the yesterday dividend. 

Interactive Brokers does not provide this particular level of information. According to [IB docs](https://interactivebrokers.github.io/tws-api/tick_types.html#ib_dividends), IB provides the following:
```
IB Dividends

This tick type provides four different comma-separated elements:

    The sum of dividends for the past 12 months (0.83 in the example below).
    The sum of dividends for the next 12 months (0.92 from the example below).
    The next dividend date (20130219 in the example below).
    The next single dividend amount (0.23 from the example below).

Example: 0.83,0.92,20130219,0.23

To receive dividend information it is sometimes necessary to direct-route rather than smart-route market data requests.
```
For the time being no dividend information will be returned in lumibot.

**Comment by SlimBeji** [comment]
@neilsmurphy I started working on this matter on the dev branch. Unfortunately, I did not finish it yet.
