### ISSUE TITLE
Naive time - no tzinfo set

### ISSUE THREAD

**Issue by grzesir** [Lumiwealth/lumibot#399]
@jimwhite @fovi-com i think an update you made to Lumibot recently created this issue:

When I try and run my strategy that executes properly on a range of ETFs on GOOG I receive the following error:

Error get_last_price from Polygon:
Naive time - no tzinfo set

The first couple of Polygon retrievals seem to work but once the error occurs to repeats for until I abort the script.

Progress |███████-------------------------------------------------------------------|  10.27%  [Elapsed: 0:00:13 ETA: 0:02:00] Portfolio Val: 14,510.40************************* Date: 2023-02-07 09:30:00-05:00 Underlying: 104.0 *************************
Progress |███████-------------------------------------------------------------------|  10.55%  [Elapsed: 0:00:13 ETA: 0:01:57] Portfolio Val: 14,510.40************************* Date: 2023-02-08 09:30:00-05:00 Underlying: 103.0 *************************
Progress |████████------------------------------------------------------------------|  10.82%  [Elapsed: 0:00:13 ETA: 0:01:53] Portfolio Val: 14,510.40************************* Date: 2023-02-09 09:30:00-05:00 Underlying: 101.0 *************************
Error get_last_price from Polygon: Naive time - no tzinfo set
Error get_last_price from Polygon: Naive time - no tzinfo set

**Comment by jimwhite** [comment]
Can you try applying https://github.com/Lumiwealth/lumibot/pull/397 ?  That will refresh your cache files and while I doubt that will fix it we'll be on the same page.  

I'd like to reproduce the failure but will need more information.  One change I'd make is this:

diff --git a/lumibot/backtesting/polygon_backtesting.py b/lumibot/backtesting/polygon_backtesting.py
index 820f8e3d..d09d3155 100644
--- a/lumibot/backtesting/polygon_backtesting.py
+++ b/lumibot/backtesting/polygon_backtesting.py
@@ -257,7 +257,7 @@ class PolygonDataBacktesting(PandasData):
             dt = self.get_datetime()
             self._update_pandas_data(asset, quote, 1, timestep, dt, update_data_store=True)
         except Exception as e:
-            print(f"Error get_last_price from Polygon: {e}")
+            print(f"Error get_last_price from Polygon: {asset=} {quote=} {timestep=} {dt=} {e}")
 
         return super().get_last_price(asset=asset, quote=quote, exchange=exchange)

**Comment by grzesir** [comment]
@jimwhite ok merged #397 

I don't think the code you posted will fix the issue, if anything it might catch it to prevent a crash. It seems like for some reason your earlier changes are creating a mismatch of tzinfo

Here's more details on the issue:

irvshapiro@makewithtech — Today at 5:28 PM
Thank you.  If there is a workaround please let me know.

irvshapiro@makewithtech — Today at 5:31 PM
Here is the github URL if he wants to use it for testing.  On line 107 of option_iron_condor_backtest_mwt.py just change the symbol to a non ETF symbol such as GOOG or AAPL.

There is also a flag at the top of this file to force it to use a local version of lumibot.   Set use_local_lumibot = True.

Thanks for looking into this so quickly. 
https://github.com/ishapiro/iron_condor_lumibot_example

**Comment by jimwhite** [comment]
Right, I don't think that change is likely to fix the problem unless the cache files got wonky as part of the earlier changes.  I have seen naive time errors along the way but for what I'm running now things appear fine.

The changing the error message as shown above will provide the details I need to (hopefully) reproduce the problem.

**Comment by grzesir** [comment]
@jimwhite i actually have had this issue as well, it's very easy to reproduce and seems to happen in many situations. do you need code to reproduce it? The link provided can do this (and it's a great algo too!), or I can provide you with more code to reproduce this if you need

**Comment by jimwhite** [comment]
> @jimwhite i actually have had this issue as well, it's very easy to reproduce and seems to happen in many situations. do you need code to reproduce it? The link provided can do this (and it's a great algo too!), or I can provide you with more code to reproduce this if you need

Ah, overlooked the link.  I've got it and upgraded my Polygon for options.  Running it now.   Should be able to get it sorted by tomorrow.

**Comment by grzesir** [comment]
> > @jimwhite i actually have had this issue as well, it's very easy to reproduce and seems to happen in many situations. do you need code to reproduce it? The link provided can do this (and it's a great algo too!), or I can provide you with more code to reproduce this if you need
> 
> Ah, overlooked the link. I've got it and upgraded my Polygon for options. Running it now. Should be able to get it sorted by tomorrow.

Awesome! Really appreciate all your work on this. Definitely noticing a good speed improvement with backtests since your changes.

I added the extra debug message so that I can catch this issue and send you the results as well `print(f"Error get_last_price from Polygon: {asset=} {quote=} {timestep=} {dt=} {e}")`

**Comment by jimwhite** [comment]
Can you share the parameters for OptionsIronCondorMWT?  I'm using the defaults as they come from the repo (AMZN etc - https://github.com/ishapiro/iron_condor_lumibot_example/blob/5cbd88a25c1544287e080a30b4b41047f8601a56/options_iron_condor_backtest_mwt.py#L107) and its been running for hours and for quite a while now I just get these:

```
Downloading data for AMZN 2029-11-30 103.0 CALL / USD 'minute' from Polygon...:  92%|█████████████████████████████████   | 11/12 [00:01<00:00,  9.46it/s]
2024-03-13 23:09:33,764: root: ERROR: Unable to find option contract for AMZN 2029-12-01 103.0 CALL

Downloading data for AMZN 2029-12-01 103.0 CALL / USD 'minute' from Polygon...:   0%|                    
```

**Comment by jimwhite** [comment]
I'm doubting that the problem is very recent.  I tried `pip install lumibot==3.1.14` and get the same errors:
```
2024-03-14 00:13:50,583: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the initialize lifecycle method
2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 08:30:00-05:00
2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_market_opens lifecycle method
2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 09:30:00-05:00
2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_starting_trading lifecycle method
2024-03-14 00:13:51,053: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-14 00:13:51[0m
2024-03-14 00:13:53,251: root: INFO: Error getting last price for (AAPL 2023-03-17 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-17 144.0 CALL) is outside of the data's date range (2023-02-21 10:18:00-05:00 to 2023-03-17 15:25:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
2024-03-14 00:13:53,693: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-18 144.0 CALL[0m
2024-03-14 00:13:54,480: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-19 144.0 CALL[0m
2024-03-14 00:13:55,104: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-20 144.0 CALL[0m
2024-03-14 00:13:55,833: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-21 144.0 CALL[0m
2024-03-14 00:13:56,462: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-22 144.0 CALL[0m
2024-03-14 00:13:57,112: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-23 144.0 CALL[0m
2024-03-14 00:13:59,089: root: INFO: Error getting last price for (AAPL 2023-03-24 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-24 144.0 CALL) is outside of the data's date range (2023-02-02 09:51:00-05:00 to 2023-03-24 15:31:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
2024-03-14 00:13:59,537: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-25 144.0 CALL[0m
```

**Comment by grzesir** [comment]
> I'm doubting that the problem is very recent.  I tried `pip install lumibot==3.1.14` and get the same errors:
> 
> ```
> 
> 2024-03-14 00:13:50,583: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the initialize lifecycle method
> 
> 2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 08:30:00-05:00
> 
> 2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_market_opens lifecycle method
> 
> 2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 09:30:00-05:00
> 
> 2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_starting_trading lifecycle method
> 
> 2024-03-14 00:13:51,053: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-14 00:13:51[0m
> 
> 2024-03-14 00:13:53,251: root: INFO: Error getting last price for (AAPL 2023-03-17 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-17 144.0 CALL) is outside of the data's date range (2023-02-21 10:18:00-05:00 to 2023-03-17 15:25:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
> 
> 2024-03-14 00:13:53,693: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-18 144.0 CALL[0m
> 
> 2024-03-14 00:13:54,480: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-19 144.0 CALL[0m
> 
> 2024-03-14 00:13:55,104: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-20 144.0 CALL[0m
> 
> 2024-03-14 00:13:55,833: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-21 144.0 CALL[0m
> 
> 2024-03-14 00:13:56,462: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-22 144.0 CALL[0m
> 
> 2024-03-14 00:13:57,112: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-23 144.0 CALL[0m
> 
> 2024-03-14 00:13:59,089: root: INFO: Error getting last price for (AAPL 2023-03-24 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-24 144.0 CALL) is outside of the data's date range (2023-02-02 09:51:00-05:00 to 2023-03-24 15:31:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
> 
> 2024-03-14 00:13:59,537: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-25 144.0 CALL[0m
> 
> ```
> 
> 
> 
> I don't know whether the parameters that I checked out are correct.  I see these problems with the defaults as the current head of the ic repo and when changing the symbol and using a different date range.
> 
> 

@jimwhite what do you mean? I don't see the no tz info error anywhere in the logs you posted

**Comment by grzesir** [comment]
> I'm doubting that the problem is very recent.  I tried `pip install lumibot==3.1.14` and get the same errors:
> 
> ```
> 
> 2024-03-14 00:13:50,583: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the initialize lifecycle method
> 
> 2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 08:30:00-05:00
> 
> 2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_market_opens lifecycle method
> 
> 2024-03-14 00:13:51,052: root: INFO: Current backtesting datetime 2023-02-01 09:30:00-05:00
> 
> 2024-03-14 00:13:51,052: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] Executing the before_starting_trading lifecycle method
> 
> 2024-03-14 00:13:51,053: asyncio: INFO: [ic-AAPL-0.16delta-40duration-7exit-7hold] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-14 00:13:51[0m
> 
> 2024-03-14 00:13:53,251: root: INFO: Error getting last price for (AAPL 2023-03-17 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-17 144.0 CALL) is outside of the data's date range (2023-02-21 10:18:00-05:00 to 2023-03-17 15:25:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
> 
> 2024-03-14 00:13:53,693: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-18 144.0 CALL[0m
> 
> 2024-03-14 00:13:54,480: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-19 144.0 CALL[0m
> 
> 2024-03-14 00:13:55,104: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-20 144.0 CALL[0m
> 
> 2024-03-14 00:13:55,833: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-21 144.0 CALL[0m
> 
> 2024-03-14 00:13:56,462: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-22 144.0 CALL[0m
> 
> 2024-03-14 00:13:57,112: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-23 144.0 CALL[0m
> 
> 2024-03-14 00:13:59,089: root: INFO: Error getting last price for (AAPL 2023-03-24 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-24 144.0 CALL) is outside of the data's date range (2023-02-02 09:51:00-05:00 to 2023-03-24 15:31:00-04:00). This could be because the data for this asset does not exist for the date you are looking for, or something else.
> 
> 2024-03-14 00:13:59,537: root: ERROR: [31mUnable to find option contract for AAPL 2023-03-25 144.0 CALL[0m
> 
> ```
> 
> 
> 
> I don't know whether the parameters that I checked out are correct.  I see these problems with the defaults as the current head of the ic repo and when changing the symbol and using a different date range.
> 
> 

Sorry just read your earlier post. I think this is because your polygon sponges is incorrect. Have you double checked that you are passing then correct polygon api key to Lumibot?

**Comment by jimwhite** [comment]
As I said above, I added Starter level Options to my Polygon subscription.  It has 2 years and 100% coverage but does not include trades (do I need that too with a Developer sub?).   I've run polygon_testing_api.py and option_testing.py successfully on both the symbol at HEAD (SPY) and with stocks (AAPL, AMZN).

I expect the reason the tzinfo errors don't appear is because the no data errors happen first ("Error getting last price for (AAPL 2023-03-17 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-17 144.0 CALL) is outside of the data's date range (2023-02-21 10:18:00-05:00 to 2023-03-17 15:25:00-04:00).").

This comment in the ic code makes plain that the particular parameters matter:
```
    # IMS Replaced with parameters from the driver program. See set_parameters method below
    # Symbols testing: GLD, SPY, QQQ, IWM  -- check the strike step size depending on the ETF
```

I've run the ic code on lumibot 3.1.14 and 3.2.0 and get these same errors.  Can you try with one of those versions and share with me the complete set of parameters (options_iron_condor_backtest_mwt.py lines 107 thru 129) you're using?

**Comment by grzesir** [comment]
> As I said above, I added Starter level Options to my Polygon subscription.  It has 2 years and 100% coverage but does not include trades (do I need that too with a Developer sub?).   I've run polygon_testing_api.py and option_testing.py successfully on both the symbol at HEAD (SPY) and with stocks (AAPL, AMZN).
> 
> 
> 
> I expect the reason the tzinfo errors don't appear is because the no data errors happen first ("Error getting last price for (AAPL 2023-03-17 144.0 CALL, USD): The date you are looking for (2023-02-01 09:30:00-05:00) for (AAPL 2023-03-17 144.0 CALL) is outside of the data's date range (2023-02-21 10:18:00-05:00 to 2023-03-17 15:25:00-04:00).").
> 
> 
> 
> This comment in the ic code makes plain that the particular parameters matter:
> 
> ```
> 
>     # IMS Replaced with parameters from the driver program. See set_parameters method below
> 
>     # Symbols testing: GLD, SPY, QQQ, IWM  -- check the strike step size depending on the ETF
> 
> ```
> 
> 
> 
> I've run the ic code on lumibot 3.1.14 and 3.2.0 and get these same errors.  Can you try with one of those versions and share with me the complete set of parameters (options_iron_condor_backtest_mwt.py lines 107 thru 129) you're using?

Have you double checked your api keys? Also did you check that has paid subscription is false? You need both an options subscription and stocks subscription to set that value to true. I don't have any trouble running backtests (although have not tried running this specific code yet)

Either way, I think your last changes may have fixed the issue. I haven't seen the tzinfo error come up for a few days now. Will let you know if I see it again, or if anyone else sees it

**Comment by grzesir** [comment]
Just confirmed with Irv, the tzinfo issue went away with your last update. Thank you!

Closing this issue now
