### ISSUE TITLE
Issue duckdb conversion

### ISSUE THREAD

**Issue by Daniel-ltw** [Lumiwealth/lumibot#414]
<img width="1346" alt="image" src="https://github.com/Lumiwealth/lumibot/assets/925271/5f928203-a470-44bc-88fe-aeb1444e696e">

Is there any way to resolve to this issue?

**Comment by grzesir** [comment]
What code caused this error? Never seen it before

Robert Grzesik 347-635-3416

**Comment by Daniel-ltw** [comment]
```
 self.get_historical_prices(self.base, 50, 'day', quote=self.quote).df
```

Was trying to backtest on binance and ccxt.

**Comment by grzesir** [comment]
This is a question for @mrchaos , who created this feature. @mrchaos any ideas how to fix this? 

I also don't think we have documentation for this yet

**Comment by grzesir** [comment]
As an aside: it seems like we should be using a different type for duckdb. Crypto can have both very large and very small values, so I don't think double is the appropriate data type. I think can either use something like bigint and move the decimals, or save it as a string.

**Comment by Daniel-ltw** [comment]
Drop a breakpoint before the insert and the culprit is the volume column value. 

Will test running it with bigint now and see how that works. 
If this goes well, will put in a pr for it.

**Comment by grzesir** [comment]
Awesome that sounds great, let me know how it goes. Just keep in mind the
column will need to be able to handle decimal places somehow.

Robert Grzesik 347-635-3416

**Comment by Daniel-ltw** [comment]
Yup. DuckDB allows us to use decimal for the columns. 

```
con.execute("""CREATE TABLE IF NOT EXISTS candles (
                            datetime DATETIME,
                            open DECIMAL, high DECIMAL, low DECIMAL, close DECIMAL, volume DECIMAL, missing INTEGER)""")
```

Just need to update line 230-232 to the above. 

Will drop in a PR for this small change. 

The rest of the prices were in float but was also throwing errors, which cause the trade_cost calculation in the backtesting_broker to fail. The above change should address this issue.

**Comment by Daniel-ltw** [comment]
PR created. https://github.com/Lumiwealth/lumibot/pull/416

**Comment by grzesir** [comment]
Great solution! Merged it in, will include this in our next release

Robert Grzesik 347-635-3416

**Comment by Daniel-ltw** [comment]
Has been merged. Will close this issue for now.
