### ISSUE TITLE
Speed up backtesting

### ISSUE THREAD

**Issue by ktlim86** [Lumiwealth/lumibot#491]
Hi,

I would like to ask if there is a way to speed up backtesting. I will try running the following code

```
MyStrategy.backtest(
    YahooDataBacktesting,
    backtesting_start,
    backtesting_end,
    logfile=logfile,
)
```

But it seem like the backtesting is running minute by minute. Not sure if this is the behaviour. I am trying to search the documentation but there is no luck.

**Comment by ktlim86** [comment]
I have managed to find it. Can

**Comment by grzesir** [comment]
If you change sleeptime to 1D it should go much faster, especially since
yahoo doesn’t support minute backtests

Robert Grzesik 347-635-3416
