### ISSUE TITLE
ThetaData username/password required for using YahooDataBacktesting

### ISSUE THREAD

**Issue by Tyler-Dunham** [Lumiwealth/lumibot#549]
I am trying to use YahooDataBacktesting and keep getting this error: 

`Please set `thetadata_username` and `thetadata_password` in the backtest() function if you are using ThetaDataBacktesting`

I am simply not using ThetaDataBacktesting. This is coming from Strategy.backtest() and passing in any datasource_class returns the same error. 

`BuyHold.backtest(YahooDataBacktesting, start, end)`

**Comment by seans11** [comment]
I was receiving the same error too.  I had an issue with my code where I was calling the `trader.run_all()` incorrectly.

Try running this example exactly as it is.  This worked for me just now:
[Lumiwealth Backtesting](https://lumibot.lumiwealth.com/backtesting.yahoo.html)

**Comment by grzesir** [comment]
@Tyler-Dunham @seans11 this bug is fixed now, please upgrade to v3.7.3
